### ISSUE TITLE
Multiple Selection Dropdown closes onchange instead of onBlur

### ISSUE THREAD

**Issue by globophobe** [nightswinger/vue-fomantic-ui#1]
Hey this is really great! 

One thing, multiple selection dropdown closes onchange. 

This differs from Fomantic UI, which closes multiple selection dropdowns onBlur.

**Comment by nightswinger** [comment]
Thanks for feedback.
I will check and fix it next version.

**Comment by nightswinger** [comment]
fix this v0.11.0
