### ISSUE TITLE
The filename of "module" and "import" of "exports" in package.json is not correct.

### ISSUE THREAD

**Issue by Akuyou-study** [nightswinger/vue-fomantic-ui#29]
When I try to import the "vue-fomantic-ui" in the main.ts that create App, there will always an error message:

>  Internal server error: Failed to resolve entry for package vue- "fomantic-" ui . The package may have incorrect main/module/exports specified in its package.json.

So I try to check the package.json of "vue-fomantic-ui" and find out that the value of "module" attribute and "import" of "exports" is "./dist/vue-fomantic-ui.es.js", which is not matched to the filename "vue-fomantic-ui.mjs" under dist folder.

After modifying the value to "./dist/vue-fomantic-ui.mjs"，I can successfully import this package and use fomantic UI.

I install "vue-fomantic-ui" version is 0.15.0

**Comment by nightswinger** [comment]
Thanks for letting me know.
I fixed this in v0.15.1.
