### ISSUE TITLE
How does the rating component work?

### ISSUE THREAD

**Issue by jjtbsomhorst** [nightswinger/vue-fomantic-ui#4]
Hi, 
the docs are a bit minimal. How is the rating component actually working? Does it support v-model? Any events that we can use to get the actual value?

**Comment by nightswinger** [comment]
thanks for comment.
Rating component currently does not support v-model and not emit any events.

**Comment by jsomhorst** [comment]
so,, what is the use case of it then?

**Comment by jjtbsomhorst** [comment]
but if v-model is not supported how to get the value of the component?
