### ISSUE TITLE
"event.Path" doesnot work on firefox

### ISSUE THREAD

**Issue by ahmed6262445** [nightswinger/vue-fomantic-ui#5]
The code snippet attached below does not work for firefox, is working only for chromium based browsers.
https://github.com/nightswinger/vue-fomantic-ui/blob/master/src/modules/Sidebar/Sidebar.tsx

![image](https://user-images.githubusercontent.com/57043614/159578242-90694a78-510c-46f8-8f12-5bdc488f72fb.png)

![image](https://user-images.githubusercontent.com/57043614/159578473-7b7a0610-fe26-4211-a177-baa9d654d1e5.png)

**Comment by nightswinger** [comment]
thanks for bug report.
I will work on it.
